package vista;


import Datos.Nodo_String;
import Datos.Almacenar;
import Datos.Arbol;
import Datos.Clasificacion;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sulay Cupítra y Ivan Vargas
 */
public class Info_Vital extends javax.swing.JFrame {

    /**
     * Creates new form agregar_arbol
     */
    public Info_Vital() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jFileChooser1 = new javax.swing.JFileChooser();
        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        add_books = new javax.swing.JButton();
        add_temas = new javax.swing.JButton();
        add_subtemas = new javax.swing.JButton();
        retornar = new javax.swing.JToggleButton();
        add_files = new javax.swing.JButton();
        full_book = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        escribir = new javax.swing.JTextArea();
        Show_inventario = new javax.swing.JButton();
        inventario_previa = new javax.swing.JButton();
        buscar_inventario = new javax.swing.JButton();
        delated_inventario = new javax.swing.JButton();
        Eliminar_previa = new javax.swing.JButton();
        buscar_previa = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Pregunta = new javax.swing.JMenuItem();
        exito = new javax.swing.JMenuItem();
        abbout = new javax.swing.JMenuItem();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Datos/ajaj.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        add_books.setText("Agregar Libros");
        add_books.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_booksActionPerformed(evt);
            }
        });

        add_temas.setText("Agregar temas");
        add_temas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_temasActionPerformed(evt);
            }
        });

        add_subtemas.setText("Agregar subtemas");
        add_subtemas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_subtemasActionPerformed(evt);
            }
        });

        retornar.setText("return");
        retornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retornarActionPerformed(evt);
            }
        });

        add_files.setText("agregar archivos");
        add_files.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_filesActionPerformed(evt);
            }
        });

        full_book.setText("Agregar Libro completo");
        full_book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                full_bookActionPerformed(evt);
            }
        });

        escribir.setColumns(20);
        escribir.setRows(5);
        jScrollPane2.setViewportView(escribir);

        Show_inventario.setText("Mostrar inventario");
        Show_inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Show_inventarioActionPerformed(evt);
            }
        });

        inventario_previa.setText("mostrar info previa");
        inventario_previa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventario_previaActionPerformed(evt);
            }
        });

        buscar_inventario.setText("buscar inventario");
        buscar_inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar_inventarioActionPerformed(evt);
            }
        });

        delated_inventario.setText("Eliminar inventario");
        delated_inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delated_inventarioActionPerformed(evt);
            }
        });

        Eliminar_previa.setText("Eliminar info previa");
        Eliminar_previa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar_previaActionPerformed(evt);
            }
        });

        buscar_previa.setText("buscar info previa");
        buscar_previa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar_previaActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        Pregunta.setText("ayuda");
        Pregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreguntaActionPerformed(evt);
            }
        });
        jMenu1.add(Pregunta);

        exito.setText("salir");
        exito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitoActionPerformed(evt);
            }
        });
        jMenu1.add(exito);

        abbout.setText("about");
        abbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abboutActionPerformed(evt);
            }
        });
        jMenu1.add(abbout);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(add_books, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(full_book, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(inventario_previa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(add_temas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(add_subtemas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(add_files)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 815, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Show_inventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buscar_inventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(retornar)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Eliminar_previa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(delated_inventario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buscar_previa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(full_book)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(add_books)
                        .addGap(18, 18, 18)
                        .addComponent(add_temas)
                        .addGap(16, 16, 16)
                        .addComponent(add_subtemas)
                        .addGap(18, 18, 18)
                        .addComponent(inventario_previa))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Show_inventario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buscar_inventario)
                                .addGap(13, 13, 13)
                                .addComponent(buscar_previa)
                                .addGap(20, 20, 20)
                                .addComponent(delated_inventario)
                                .addGap(18, 18, 18)
                                .addComponent(Eliminar_previa)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(add_files)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(retornar)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitoActionPerformed
       System.exit(1);
    }//GEN-LAST:event_exitoActionPerformed

    private void PreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreguntaActionPerformed
        JOptionPane.showMessageDialog(null, "Este es el manual para manejar este formato:\n"
                + "Agregar) Solo permite ingresar cuantitativamente la cantidad de archivos por los cuales desea agregar al libro.\n"
                + "Area) escriba el conetinido del archivo.\n"
                + "Tema) Biologia, Matematicas, Fisica y literatura\n"
                + "subtema) la especialidad del tema  \n"
                + "\npor favor no utilizar la tecla enter para ejecutar el programa, se debe usar solamente los botones para ejecutar");
    }//GEN-LAST:event_PreguntaActionPerformed

    private void abboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abboutActionPerformed
        JOptionPane.showMessageDialog(null, "Ivan 2000 bibbloteca v.10"
               + "\nAutores:"
               + "\nIvan Vargas"
               + "\nSulay Cupitra"
               + "\n asignatura: Estructuras de datos"
               + "\n fecha 18 Septiembre 2017");
    }//GEN-LAST:event_abboutActionPerformed
    Almacenar ar=new Almacenar();
    Arbol libro = new Arbol();
    Arbol tema = new Arbol();
    Arbol subtema= new Arbol();
    
    private void add_booksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_booksActionPerformed
        Arbol slibro = new Arbol();
        ar.libros_Agregar();
        libro=slibro;
    int resp=JOptionPane.showConfirmDialog(null,"¿Estas seguro de guardar?");
      if (JOptionPane.OK_OPTION == resp){
        JOptionPane.showMessageDialog(null, "LA INFORMACION SE HA ALMACENADO EXITOSAMENTE");
      }
      else{
     JOptionPane.showMessageDialog(null, "LA INFORMACION SE NO HA ALMACENADO EXITOSAMENTE");
   }
    }//GEN-LAST:event_add_booksActionPerformed

    private void add_temasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_temasActionPerformed
       Arbol stema = new Arbol();
       ar.temas_Agregar();
       tema=stema;
      int resp=JOptionPane.showConfirmDialog(null,"¿Estas seguro de guardar?");
      if (JOptionPane.OK_OPTION == resp){
      JOptionPane.showMessageDialog(null, "LA INFORMACION SE HA ALMACENADO EXITOSAMENTE");
      }
      else{
     JOptionPane.showMessageDialog(null, "LA INFORMACION SE NO HA ALMACENADO EXITOSAMENTE");
   }    
    }//GEN-LAST:event_add_temasActionPerformed

    private void add_subtemasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_subtemasActionPerformed
        Arbol ssubtema= new Arbol();
        ar.subtemas_Agregar();
        subtema=ssubtema;
       int resp=JOptionPane.showConfirmDialog(null,"¿Estas seguro de guardar?");
      if (JOptionPane.OK_OPTION == resp){
       JOptionPane.showMessageDialog(null, "LA INFORMACION SE HA ALMACENADO EXITOSAMENTE");
      }
      else{
     JOptionPane.showMessageDialog(null, "LA INFORMACION SE NO HA ALMACENADO EXITOSAMENTE");
      }
    }//GEN-LAST:event_add_subtemasActionPerformed

    private void retornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retornarActionPerformed
          Menu_Bibloteca abrir= new Menu_Bibloteca();
          abrir.setVisible(true);
    }//GEN-LAST:event_retornarActionPerformed

    private void add_filesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_filesActionPerformed
        String val = this.escribir.getText();
        Nodo_String nuevo= new Nodo_String(val);
        nuevo.guardad(val);
        
    }//GEN-LAST:event_add_filesActionPerformed
Clasificacion administrador=new Clasificacion();
    private void full_bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_full_bookActionPerformed
        administrador.ejecutar();
    }//GEN-LAST:event_full_bookActionPerformed

    private void Show_inventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Show_inventarioActionPerformed
        ar.mostra_inventario();
    }//GEN-LAST:event_Show_inventarioActionPerformed

    private void inventario_previaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventario_previaActionPerformed
        administrador.inventario();
    }//GEN-LAST:event_inventario_previaActionPerformed

    private void buscar_inventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar_inventarioActionPerformed
        ar.buscar_inventario();
    }//GEN-LAST:event_buscar_inventarioActionPerformed

    private void buscar_previaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar_previaActionPerformed
        administrador.buscar_inventario();
    }//GEN-LAST:event_buscar_previaActionPerformed

    private void delated_inventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delated_inventarioActionPerformed
        ar.eliminar_inventario();
    }//GEN-LAST:event_delated_inventarioActionPerformed

    private void Eliminar_previaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar_previaActionPerformed
      administrador.eliminar();
    }//GEN-LAST:event_Eliminar_previaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Info_Vital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Info_Vital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Info_Vital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Info_Vital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Info_Vital().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Eliminar_previa;
    private javax.swing.JMenuItem Pregunta;
    private javax.swing.JButton Show_inventario;
    private javax.swing.JMenuItem abbout;
    private javax.swing.JButton add_books;
    private javax.swing.JButton add_files;
    private javax.swing.JButton add_subtemas;
    private javax.swing.JButton add_temas;
    private javax.swing.JButton buscar_inventario;
    private javax.swing.JButton buscar_previa;
    private javax.swing.JButton delated_inventario;
    private javax.swing.JTextArea escribir;
    private javax.swing.JMenuItem exito;
    private javax.swing.JButton full_book;
    private javax.swing.JButton inventario_previa;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToggleButton retornar;
    // End of variables declaration//GEN-END:variables
}
